/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgribotRouteImport } from './routes/agribot'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BuyersRouteImport } from './routes/buyers'
import { Route as CropsRouteImport } from './routes/crops'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DecisionRouteImport } from './routes/decision'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as FpoRouteImport } from './routes/fpo'
import { Route as LogisticsRouteImport } from './routes/logistics'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as StorageRouteImport } from './routes/storage'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgribotRoute = AgribotRouteImport.update({
  id: '/agribot',
  path: '/agribot',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyersRoute = BuyersRouteImport.update({
  id: '/buyers',
  path: '/buyers',
  getParentRoute: () => rootRouteImport,
} as any)
const CropsRoute = CropsRouteImport.update({
  id: '/crops',
  path: '/crops',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionRoute = DecisionRouteImport.update({
  id: '/decision',
  path: '/decision',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const FpoRoute = FpoRouteImport.update({
  id: '/fpo',
  path: '/fpo',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsRoute = LogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageRoute = StorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agribot': typeof AgribotRoute
  '/auth': typeof AuthRoute
  '/buyers': typeof BuyersRoute
  '/crops': typeof CropsRoute
  '/dashboard': typeof DashboardRoute
  '/decision': typeof DecisionRoute
  '/forecast': typeof ForecastRoute
  '/fpo': typeof FpoRoute
  '/logistics': typeof LogisticsRoute
  '/markets': typeof MarketsRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/storage': typeof StorageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agribot': typeof AgribotRoute
  '/auth': typeof AuthRoute
  '/buyers': typeof BuyersRoute
  '/crops': typeof CropsRoute
  '/dashboard': typeof DashboardRoute
  '/decision': typeof DecisionRoute
  '/forecast': typeof ForecastRoute
  '/fpo': typeof FpoRoute
  '/logistics': typeof LogisticsRoute
  '/markets': typeof MarketsRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/storage': typeof StorageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agribot': typeof AgribotRoute
  '/auth': typeof AuthRoute
  '/buyers': typeof BuyersRoute
  '/crops': typeof CropsRoute
  '/dashboard': typeof DashboardRoute
  '/decision': typeof DecisionRoute
  '/forecast': typeof ForecastRoute
  '/fpo': typeof FpoRoute
  '/logistics': typeof LogisticsRoute
  '/markets': typeof MarketsRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/storage': typeof StorageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agribot'
    | '/auth'
    | '/buyers'
    | '/crops'
    | '/dashboard'
    | '/decision'
    | '/forecast'
    | '/fpo'
    | '/logistics'
    | '/markets'
    | '/notifications'
    | '/orders'
    | '/payments'
    | '/profile'
    | '/storage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agribot'
    | '/auth'
    | '/buyers'
    | '/crops'
    | '/dashboard'
    | '/decision'
    | '/forecast'
    | '/fpo'
    | '/logistics'
    | '/markets'
    | '/notifications'
    | '/orders'
    | '/payments'
    | '/profile'
    | '/storage'
  id:
    | '__root__'
    | '/'
    | '/agribot'
    | '/auth'
    | '/buyers'
    | '/crops'
    | '/dashboard'
    | '/decision'
    | '/forecast'
    | '/fpo'
    | '/logistics'
    | '/markets'
    | '/notifications'
    | '/orders'
    | '/payments'
    | '/profile'
    | '/storage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgribotRoute: typeof AgribotRoute
  AuthRoute: typeof AuthRoute
  BuyersRoute: typeof BuyersRoute
  CropsRoute: typeof CropsRoute
  DashboardRoute: typeof DashboardRoute
  DecisionRoute: typeof DecisionRoute
  ForecastRoute: typeof ForecastRoute
  FpoRoute: typeof FpoRoute
  LogisticsRoute: typeof LogisticsRoute
  MarketsRoute: typeof MarketsRoute
  NotificationsRoute: typeof NotificationsRoute
  OrdersRoute: typeof OrdersRoute
  PaymentsRoute: typeof PaymentsRoute
  ProfileRoute: typeof ProfileRoute
  StorageRoute: typeof StorageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agribot': {
      id: '/agribot'
      path: '/agribot'
      fullPath: '/agribot'
      preLoaderRoute: typeof AgribotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyers': {
      id: '/buyers'
      path: '/buyers'
      fullPath: '/buyers'
      preLoaderRoute: typeof BuyersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crops': {
      id: '/crops'
      path: '/crops'
      fullPath: '/crops'
      preLoaderRoute: typeof CropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decision': {
      id: '/decision'
      path: '/decision'
      fullPath: '/decision'
      preLoaderRoute: typeof DecisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fpo': {
      id: '/fpo'
      path: '/fpo'
      fullPath: '/fpo'
      preLoaderRoute: typeof FpoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics': {
      id: '/logistics'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof LogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage': {
      id: '/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof StorageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgribotRoute: AgribotRoute,
  AuthRoute: AuthRoute,
  BuyersRoute: BuyersRoute,
  CropsRoute: CropsRoute,
  DashboardRoute: DashboardRoute,
  DecisionRoute: DecisionRoute,
  ForecastRoute: ForecastRoute,
  FpoRoute: FpoRoute,
  LogisticsRoute: LogisticsRoute,
  MarketsRoute: MarketsRoute,
  NotificationsRoute: NotificationsRoute,
  OrdersRoute: OrdersRoute,
  PaymentsRoute: PaymentsRoute,
  ProfileRoute: ProfileRoute,
  StorageRoute: StorageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
